---
- name: set profile
  template:
    src: heroku_cli.sh.j2
    dest: /etc/profile.d/heroku_cli.sh
    owner: root
    group: root
    mode: 0644

- name: download Heroku CLI installer
  uri:
    url: https://cli-assets.heroku.com/install.sh
    dest: /tmp/install_heroku_cli.sh
    creates: /tmp/install_heroku_cli.sh

- name: install tar to install Heroku CLI
  yum:
    name: tar

- name: install Heroku CLI
  command: bash -lc 'sh /tmp/install_heroku_cli.sh'
  args:
    creates: /usr/local/lib/heroku/bin/heroku

- include_tasks: set_up_for_local_command.yml
  when: heroku_cli_support_local_command
